timestamp: '2026-03-18 08:10:47'
config:
  exp: td3_lift
  total_timesteps: 2000000
  num_cpu: 6
  norm_train:
    norm_obs: true
    norm_reward: false
    clip_obs: 10.0
    training: true
  env_config:
    reward_shaping: true
    control_freq: 20
    horizon: 256
    action_penalty: 0
    action_smooth: 0
    kp: 150.0
    reward_scale: 1.0
    controller: cart
  td3_config:
    seed: 42
    policy: MlpPolicy
    learning_rate: 0.0003
    buffer_size: 2000000
    learning_starts: 10000
    batch_size: 256
    tau: 0.005
    gamma: 0.98
    action_noise: NormalActionNoise(mu=[0. 0. 0. 0. 0. 0. 0.], sigma=[0.2 0.2 0.2
      0.2 0.2 0.2 0.2])
    policy_delay: 2
    target_policy_noise: 0.25
    target_noise_clip: 0.5
    gradient_steps: 1
    policy_kwargs:
      net_arch:
      - 400
      - 300
    verbose: 1
    device: cuda
