_wandb:
    value:
        cli_version: 0.25.0
        e:
            2ad6y0axog3a4ixs5wxb3kqh6b36xotv:
                codePath: scripts/sync2wandb.py
                codePathLocal: scripts/sync2wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "489997189120"
                        used: "33077731328"
                email: zixinzhao608@gmail.com
                executable: /home/user/zhaozixin/anaconda3/envs/grasp_env/bin/python
                git:
                    commit: af9298db83335f00c11d3ac6580e04bf6a4f1e52
                    remote: git@github.com:ZzXwANT/cloud-GPU-data.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-1cc981f2-e5d2-1802-7ce9-70ef342baf13
                host: aitechlab-System-Product-Name
                memory:
                    total: "16693276672"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /home/user/zhaozixin/proj/cloud-GPU-data/scripts/sync2wandb.py
                python: CPython 3.10.19
                root: /home/user/zhaozixin/proj/cloud-GPU-data
                startedAt: "2026-03-15T08:17:32.189907Z"
                writerId: 2ad6y0axog3a4ixs5wxb3kqh6b36xotv
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
algo:
    value: td3_lift
base:
    value: cart_state_base
seed:
    value: 114514
tb_dir:
    value: cart_state_base/runs/td3_lift/114514-20260312_231405/tensorboard/TD3_1
